export const TEST_PRODUCTIONS = {
  1: {
    id: 1,
    title: 'Shoes',
    description: 'If a dog chews shoes whose shoes does he choose?',
    image: 'https://picsum.photos/600/600?random=1',
    tags: ['Fashion', 'Products'],
    isNew: true,
  },
  2: {
    id: 2,
    title: 'Hat',
    description: 'A stylish hat for all occasions.',
    image: 'https://picsum.photos/600/600?random=2',
    tags: ['Fashion', 'Accessories'],
    isNew: false,
  },
  3: {
    id: 3,
    title: 'Watch',
    description: 'Keep track of time with this elegant watch.',
    image: 'https://picsum.photos/600/600?random=3',
    tags: ['Fashion', 'Accessories'],
    isNew: true,
  },
  4: {
    id: 4,
    title: 'Bag',
    description: 'A spacious bag for your daily needs.',
    image: 'https://picsum.photos/600/600?random=4',
    tags: ['Fashion', 'Products'],
    isNew: false,
  },
  5: {
    id: 5,
    title: 'Sunglasses',
    description: 'Protect your eyes with these stylish sunglasses.',
    image: 'https://picsum.photos/600/600?random=5',
    tags: ['Fashion', 'Accessories'],
    isNew: true,
  },
  6: {
    id: 6,
    title: 'Jacket',
    description: 'Stay warm with this fashionable jacket.',
    image: 'https://picsum.photos/600/600?random=6',
    tags: ['Fashion', 'Clothing'],
    isNew: false,
  },
  7: {
    id: 7,
    title: 'Belt',
    description: 'A durable belt for everyday use.',
    image: 'https://picsum.photos/600/600?random=7',
    tags: ['Fashion', 'Accessories'],
    isNew: true,
  },
  8: {
    id: 8,
    title: 'Scarf',
    description: 'A cozy scarf for chilly days.',
    image: 'https://picsum.photos/600/600?random=8',
    tags: ['Fashion', 'Clothing'],
    isNew: false,
  },
  9: {
    id: 9,
    title: 'Gloves',
    description: 'Keep your hands warm with these gloves.',
    image: 'https://picsum.photos/600/600?random=9',
    tags: ['Fashion', 'Accessories'],
    isNew: true,
  },
};
